services:
  cashflow-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.develop
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USERNAME:-laravel}
    container_name: cashflow
    working_dir: /app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
      - "5173:5173"
    profiles:
      - develop
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    profiles:
      - develop

volumes:
  mariadb_data: